version: "3.9"

services:

  db:
    image: postgres:15
    container_name: habit_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: habit_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: habit_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./habit_tracker:/app/habit_tracker
      - ./habits:/app/habits
      - ./users:/app/users
      - ./notifications:/app/notifications
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: habit_celery_worker
    command: celery -A habit_tracker worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  beat:
    build: .
    container_name: habit_celery_beat
    command: celery -A habit_tracker beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    container_name: habit_nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
