# Generated by Django 6.0 on 2026-01-08 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("is_reward", models.BooleanField(default=False)),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                ("periodicity", models.PositiveSmallIntegerField(default=1)),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Время выполнения в секундах"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_to",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
